version: '3.9'

volumes:
    postgres:

services:
  postgres:
    container_name: postgres
    image: "postgres:12"
    expose:
      - "15432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/data/postgres"
    volumes:
       - postgres:/data/postgres
       - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
 
  crud:
    depends_on:
      - "postgres"
    container_name: event-crud
    image: event-crud:v1.00
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8082:8080"

  consumer:
    depends_on:
      - "postgres"
      - "crud"
    container_name: event-consumer
    image: event-consumer:v1.00
    ports:
      - "8081:8080"
     
