server:
  servlet:
    context-path: /
  port: 8080

spring:
 main:
  allow-bean-definition-overriding: true
 zipkin:
  enabled: true
  base-url: http://localhost:9411/zipkin/

  sleuth:
        enabled: true
        sampler:
          percentage: 1

management:
    endpoints:
        web:
            exposure:
                include: '* '
api:
 event:
  url: http://localhost:8085/api/event