server:
  servlet:
    context-path: /
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:15432/postgres?stringtype=unspecified}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    initialization-mode: always
    #url: jdbc:postgresql://localhost:5432/postgres?stringtype=unspecified
    #username: postgres
    #password: ''
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
camel:
    component:
        servlet:
            mapping:
                context-path: /api/*
    springboot:
        main-run-controller: true
        name: Service1
sql:
 update: update event set trans_id=:#transId ,trans_time=:#transTms ,rc_number=:#rcNum ,client_id=:#clientId ,event_count=:#eventCnt ,location_code=:#locationCd ,location_id1=:#locationId1 ,location_id2=:#locationId2 ,addr_number=:#addrNbr  where event_id = :#id       